<?php
/**
  * Implementation of hook_menu
  */
function question_list_menu() {
  $items['question-list'] = array(
    'title' => 'Questions',
    'weight' => 1,
    'type' => MENU_CALLBACK,
    'page callback' => 'question_list',
    'access arguments' => array('access question list'),
    'file' => 'includes/question_list.inc'
  );
  return $items;
}
/**
  * implementation of hook_perm
  */
function question_list_permission() {
  return array(
    'access question list' => array(
      'title' => t('Access question list'),
    ),
  );
}
/**
 * Implements hook_theme()
 */
function question_list_theme() {
  return array(
    'question_list' => array(
      'template' => 'question-list',
    ),
    'question_row' => array(
      'template' => 'question-row',
      'variables' => array(
        'entityform_id' => NULL,
        'field_number_of_votes' => NULL,
        'field_question' => NULL,
        'field_number_of_answers' => NULL,
        'field_number_of_views' => NULL,
      ),
    ),
  );
}